// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: injective/wasmx/v1/events.proto

package injective.wasmx.v1;

public final class Events {
  private Events() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EventContractExecutionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:injective.wasmx.v1.EventContractExecution)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string contract_address = 1;</code>
     * @return The contractAddress.
     */
    java.lang.String getContractAddress();
    /**
     * <code>string contract_address = 1;</code>
     * @return The bytes for contractAddress.
     */
    com.google.protobuf.ByteString
        getContractAddressBytes();

    /**
     * <code>bytes response = 2;</code>
     * @return The response.
     */
    com.google.protobuf.ByteString getResponse();

    /**
     * <code>string other_error = 3;</code>
     * @return The otherError.
     */
    java.lang.String getOtherError();
    /**
     * <code>string other_error = 3;</code>
     * @return The bytes for otherError.
     */
    com.google.protobuf.ByteString
        getOtherErrorBytes();

    /**
     * <code>string execution_error = 4;</code>
     * @return The executionError.
     */
    java.lang.String getExecutionError();
    /**
     * <code>string execution_error = 4;</code>
     * @return The bytes for executionError.
     */
    com.google.protobuf.ByteString
        getExecutionErrorBytes();
  }
  /**
   * Protobuf type {@code injective.wasmx.v1.EventContractExecution}
   */
  public static final class EventContractExecution extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:injective.wasmx.v1.EventContractExecution)
      EventContractExecutionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EventContractExecution.newBuilder() to construct.
    private EventContractExecution(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EventContractExecution() {
      contractAddress_ = "";
      response_ = com.google.protobuf.ByteString.EMPTY;
      otherError_ = "";
      executionError_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EventContractExecution();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return injective.wasmx.v1.Events.internal_static_injective_wasmx_v1_EventContractExecution_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return injective.wasmx.v1.Events.internal_static_injective_wasmx_v1_EventContractExecution_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              injective.wasmx.v1.Events.EventContractExecution.class, injective.wasmx.v1.Events.EventContractExecution.Builder.class);
    }

    public static final int CONTRACT_ADDRESS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object contractAddress_ = "";
    /**
     * <code>string contract_address = 1;</code>
     * @return The contractAddress.
     */
    @java.lang.Override
    public java.lang.String getContractAddress() {
      java.lang.Object ref = contractAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string contract_address = 1;</code>
     * @return The bytes for contractAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContractAddressBytes() {
      java.lang.Object ref = contractAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString response_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes response = 2;</code>
     * @return The response.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getResponse() {
      return response_;
    }

    public static final int OTHER_ERROR_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object otherError_ = "";
    /**
     * <code>string other_error = 3;</code>
     * @return The otherError.
     */
    @java.lang.Override
    public java.lang.String getOtherError() {
      java.lang.Object ref = otherError_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        otherError_ = s;
        return s;
      }
    }
    /**
     * <code>string other_error = 3;</code>
     * @return The bytes for otherError.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOtherErrorBytes() {
      java.lang.Object ref = otherError_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        otherError_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXECUTION_ERROR_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object executionError_ = "";
    /**
     * <code>string execution_error = 4;</code>
     * @return The executionError.
     */
    @java.lang.Override
    public java.lang.String getExecutionError() {
      java.lang.Object ref = executionError_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        executionError_ = s;
        return s;
      }
    }
    /**
     * <code>string execution_error = 4;</code>
     * @return The bytes for executionError.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExecutionErrorBytes() {
      java.lang.Object ref = executionError_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        executionError_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractAddress_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contractAddress_);
      }
      if (!response_.isEmpty()) {
        output.writeBytes(2, response_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(otherError_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, otherError_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(executionError_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, executionError_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractAddress_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, contractAddress_);
      }
      if (!response_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, response_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(otherError_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, otherError_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(executionError_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, executionError_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof injective.wasmx.v1.Events.EventContractExecution)) {
        return super.equals(obj);
      }
      injective.wasmx.v1.Events.EventContractExecution other = (injective.wasmx.v1.Events.EventContractExecution) obj;

      if (!getContractAddress()
          .equals(other.getContractAddress())) return false;
      if (!getResponse()
          .equals(other.getResponse())) return false;
      if (!getOtherError()
          .equals(other.getOtherError())) return false;
      if (!getExecutionError()
          .equals(other.getExecutionError())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTRACT_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getContractAddress().hashCode();
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponse().hashCode();
      hash = (37 * hash) + OTHER_ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getOtherError().hashCode();
      hash = (37 * hash) + EXECUTION_ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getExecutionError().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static injective.wasmx.v1.Events.EventContractExecution parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.wasmx.v1.Events.EventContractExecution parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.wasmx.v1.Events.EventContractExecution parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.wasmx.v1.Events.EventContractExecution parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.wasmx.v1.Events.EventContractExecution parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.wasmx.v1.Events.EventContractExecution parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.wasmx.v1.Events.EventContractExecution parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static injective.wasmx.v1.Events.EventContractExecution parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static injective.wasmx.v1.Events.EventContractExecution parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static injective.wasmx.v1.Events.EventContractExecution parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static injective.wasmx.v1.Events.EventContractExecution parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static injective.wasmx.v1.Events.EventContractExecution parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(injective.wasmx.v1.Events.EventContractExecution prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code injective.wasmx.v1.EventContractExecution}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:injective.wasmx.v1.EventContractExecution)
        injective.wasmx.v1.Events.EventContractExecutionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return injective.wasmx.v1.Events.internal_static_injective_wasmx_v1_EventContractExecution_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return injective.wasmx.v1.Events.internal_static_injective_wasmx_v1_EventContractExecution_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                injective.wasmx.v1.Events.EventContractExecution.class, injective.wasmx.v1.Events.EventContractExecution.Builder.class);
      }

      // Construct using injective.wasmx.v1.Events.EventContractExecution.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        contractAddress_ = "";
        response_ = com.google.protobuf.ByteString.EMPTY;
        otherError_ = "";
        executionError_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return injective.wasmx.v1.Events.internal_static_injective_wasmx_v1_EventContractExecution_descriptor;
      }

      @java.lang.Override
      public injective.wasmx.v1.Events.EventContractExecution getDefaultInstanceForType() {
        return injective.wasmx.v1.Events.EventContractExecution.getDefaultInstance();
      }

      @java.lang.Override
      public injective.wasmx.v1.Events.EventContractExecution build() {
        injective.wasmx.v1.Events.EventContractExecution result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public injective.wasmx.v1.Events.EventContractExecution buildPartial() {
        injective.wasmx.v1.Events.EventContractExecution result = new injective.wasmx.v1.Events.EventContractExecution(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(injective.wasmx.v1.Events.EventContractExecution result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.contractAddress_ = contractAddress_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.response_ = response_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.otherError_ = otherError_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.executionError_ = executionError_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof injective.wasmx.v1.Events.EventContractExecution) {
          return mergeFrom((injective.wasmx.v1.Events.EventContractExecution)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(injective.wasmx.v1.Events.EventContractExecution other) {
        if (other == injective.wasmx.v1.Events.EventContractExecution.getDefaultInstance()) return this;
        if (!other.getContractAddress().isEmpty()) {
          contractAddress_ = other.contractAddress_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getResponse() != com.google.protobuf.ByteString.EMPTY) {
          setResponse(other.getResponse());
        }
        if (!other.getOtherError().isEmpty()) {
          otherError_ = other.otherError_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getExecutionError().isEmpty()) {
          executionError_ = other.executionError_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                contractAddress_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                response_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                otherError_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                executionError_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object contractAddress_ = "";
      /**
       * <code>string contract_address = 1;</code>
       * @return The contractAddress.
       */
      public java.lang.String getContractAddress() {
        java.lang.Object ref = contractAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contractAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string contract_address = 1;</code>
       * @return The bytes for contractAddress.
       */
      public com.google.protobuf.ByteString
          getContractAddressBytes() {
        java.lang.Object ref = contractAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contractAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string contract_address = 1;</code>
       * @param value The contractAddress to set.
       * @return This builder for chaining.
       */
      public Builder setContractAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        contractAddress_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string contract_address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearContractAddress() {
        contractAddress_ = getDefaultInstance().getContractAddress();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string contract_address = 1;</code>
       * @param value The bytes for contractAddress to set.
       * @return This builder for chaining.
       */
      public Builder setContractAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        contractAddress_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString response_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes response = 2;</code>
       * @return The response.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getResponse() {
        return response_;
      }
      /**
       * <code>bytes response = 2;</code>
       * @param value The response to set.
       * @return This builder for chaining.
       */
      public Builder setResponse(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        response_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes response = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000002);
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }

      private java.lang.Object otherError_ = "";
      /**
       * <code>string other_error = 3;</code>
       * @return The otherError.
       */
      public java.lang.String getOtherError() {
        java.lang.Object ref = otherError_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          otherError_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string other_error = 3;</code>
       * @return The bytes for otherError.
       */
      public com.google.protobuf.ByteString
          getOtherErrorBytes() {
        java.lang.Object ref = otherError_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          otherError_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string other_error = 3;</code>
       * @param value The otherError to set.
       * @return This builder for chaining.
       */
      public Builder setOtherError(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        otherError_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string other_error = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOtherError() {
        otherError_ = getDefaultInstance().getOtherError();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string other_error = 3;</code>
       * @param value The bytes for otherError to set.
       * @return This builder for chaining.
       */
      public Builder setOtherErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        otherError_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object executionError_ = "";
      /**
       * <code>string execution_error = 4;</code>
       * @return The executionError.
       */
      public java.lang.String getExecutionError() {
        java.lang.Object ref = executionError_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          executionError_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string execution_error = 4;</code>
       * @return The bytes for executionError.
       */
      public com.google.protobuf.ByteString
          getExecutionErrorBytes() {
        java.lang.Object ref = executionError_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          executionError_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string execution_error = 4;</code>
       * @param value The executionError to set.
       * @return This builder for chaining.
       */
      public Builder setExecutionError(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        executionError_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string execution_error = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecutionError() {
        executionError_ = getDefaultInstance().getExecutionError();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string execution_error = 4;</code>
       * @param value The bytes for executionError to set.
       * @return This builder for chaining.
       */
      public Builder setExecutionErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        executionError_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:injective.wasmx.v1.EventContractExecution)
    }

    // @@protoc_insertion_point(class_scope:injective.wasmx.v1.EventContractExecution)
    private static final injective.wasmx.v1.Events.EventContractExecution DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new injective.wasmx.v1.Events.EventContractExecution();
    }

    public static injective.wasmx.v1.Events.EventContractExecution getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EventContractExecution>
        PARSER = new com.google.protobuf.AbstractParser<EventContractExecution>() {
      @java.lang.Override
      public EventContractExecution parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EventContractExecution> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EventContractExecution> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public injective.wasmx.v1.Events.EventContractExecution getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EventContractRegisteredOrBuilder extends
      // @@protoc_insertion_point(interface_extends:injective.wasmx.v1.EventContractRegistered)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string contract_address = 1;</code>
     * @return The contractAddress.
     */
    java.lang.String getContractAddress();
    /**
     * <code>string contract_address = 1;</code>
     * @return The bytes for contractAddress.
     */
    com.google.protobuf.ByteString
        getContractAddressBytes();

    /**
     * <code>uint64 gas_price = 3;</code>
     * @return The gasPrice.
     */
    long getGasPrice();

    /**
     * <code>bool should_pin_contract = 4;</code>
     * @return The shouldPinContract.
     */
    boolean getShouldPinContract();

    /**
     * <code>bool is_migration_allowed = 5;</code>
     * @return The isMigrationAllowed.
     */
    boolean getIsMigrationAllowed();

    /**
     * <code>uint64 code_id = 6;</code>
     * @return The codeId.
     */
    long getCodeId();

    /**
     * <code>string admin_address = 7;</code>
     * @return The adminAddress.
     */
    java.lang.String getAdminAddress();
    /**
     * <code>string admin_address = 7;</code>
     * @return The bytes for adminAddress.
     */
    com.google.protobuf.ByteString
        getAdminAddressBytes();

    /**
     * <code>string granter_address = 8;</code>
     * @return The granterAddress.
     */
    java.lang.String getGranterAddress();
    /**
     * <code>string granter_address = 8;</code>
     * @return The bytes for granterAddress.
     */
    com.google.protobuf.ByteString
        getGranterAddressBytes();

    /**
     * <code>.injective.wasmx.v1.FundingMode funding_mode = 9;</code>
     * @return The enum numeric value on the wire for fundingMode.
     */
    int getFundingModeValue();
    /**
     * <code>.injective.wasmx.v1.FundingMode funding_mode = 9;</code>
     * @return The fundingMode.
     */
    injective.wasmx.v1.Proposal.FundingMode getFundingMode();
  }
  /**
   * Protobuf type {@code injective.wasmx.v1.EventContractRegistered}
   */
  public static final class EventContractRegistered extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:injective.wasmx.v1.EventContractRegistered)
      EventContractRegisteredOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EventContractRegistered.newBuilder() to construct.
    private EventContractRegistered(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EventContractRegistered() {
      contractAddress_ = "";
      adminAddress_ = "";
      granterAddress_ = "";
      fundingMode_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EventContractRegistered();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return injective.wasmx.v1.Events.internal_static_injective_wasmx_v1_EventContractRegistered_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return injective.wasmx.v1.Events.internal_static_injective_wasmx_v1_EventContractRegistered_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              injective.wasmx.v1.Events.EventContractRegistered.class, injective.wasmx.v1.Events.EventContractRegistered.Builder.class);
    }

    public static final int CONTRACT_ADDRESS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object contractAddress_ = "";
    /**
     * <code>string contract_address = 1;</code>
     * @return The contractAddress.
     */
    @java.lang.Override
    public java.lang.String getContractAddress() {
      java.lang.Object ref = contractAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string contract_address = 1;</code>
     * @return The bytes for contractAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContractAddressBytes() {
      java.lang.Object ref = contractAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GAS_PRICE_FIELD_NUMBER = 3;
    private long gasPrice_ = 0L;
    /**
     * <code>uint64 gas_price = 3;</code>
     * @return The gasPrice.
     */
    @java.lang.Override
    public long getGasPrice() {
      return gasPrice_;
    }

    public static final int SHOULD_PIN_CONTRACT_FIELD_NUMBER = 4;
    private boolean shouldPinContract_ = false;
    /**
     * <code>bool should_pin_contract = 4;</code>
     * @return The shouldPinContract.
     */
    @java.lang.Override
    public boolean getShouldPinContract() {
      return shouldPinContract_;
    }

    public static final int IS_MIGRATION_ALLOWED_FIELD_NUMBER = 5;
    private boolean isMigrationAllowed_ = false;
    /**
     * <code>bool is_migration_allowed = 5;</code>
     * @return The isMigrationAllowed.
     */
    @java.lang.Override
    public boolean getIsMigrationAllowed() {
      return isMigrationAllowed_;
    }

    public static final int CODE_ID_FIELD_NUMBER = 6;
    private long codeId_ = 0L;
    /**
     * <code>uint64 code_id = 6;</code>
     * @return The codeId.
     */
    @java.lang.Override
    public long getCodeId() {
      return codeId_;
    }

    public static final int ADMIN_ADDRESS_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object adminAddress_ = "";
    /**
     * <code>string admin_address = 7;</code>
     * @return The adminAddress.
     */
    @java.lang.Override
    public java.lang.String getAdminAddress() {
      java.lang.Object ref = adminAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        adminAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string admin_address = 7;</code>
     * @return The bytes for adminAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAdminAddressBytes() {
      java.lang.Object ref = adminAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        adminAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GRANTER_ADDRESS_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object granterAddress_ = "";
    /**
     * <code>string granter_address = 8;</code>
     * @return The granterAddress.
     */
    @java.lang.Override
    public java.lang.String getGranterAddress() {
      java.lang.Object ref = granterAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        granterAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string granter_address = 8;</code>
     * @return The bytes for granterAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGranterAddressBytes() {
      java.lang.Object ref = granterAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        granterAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FUNDING_MODE_FIELD_NUMBER = 9;
    private int fundingMode_ = 0;
    /**
     * <code>.injective.wasmx.v1.FundingMode funding_mode = 9;</code>
     * @return The enum numeric value on the wire for fundingMode.
     */
    @java.lang.Override public int getFundingModeValue() {
      return fundingMode_;
    }
    /**
     * <code>.injective.wasmx.v1.FundingMode funding_mode = 9;</code>
     * @return The fundingMode.
     */
    @java.lang.Override public injective.wasmx.v1.Proposal.FundingMode getFundingMode() {
      injective.wasmx.v1.Proposal.FundingMode result = injective.wasmx.v1.Proposal.FundingMode.forNumber(fundingMode_);
      return result == null ? injective.wasmx.v1.Proposal.FundingMode.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractAddress_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contractAddress_);
      }
      if (gasPrice_ != 0L) {
        output.writeUInt64(3, gasPrice_);
      }
      if (shouldPinContract_ != false) {
        output.writeBool(4, shouldPinContract_);
      }
      if (isMigrationAllowed_ != false) {
        output.writeBool(5, isMigrationAllowed_);
      }
      if (codeId_ != 0L) {
        output.writeUInt64(6, codeId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(adminAddress_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, adminAddress_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(granterAddress_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, granterAddress_);
      }
      if (fundingMode_ != injective.wasmx.v1.Proposal.FundingMode.Unspecified.getNumber()) {
        output.writeEnum(9, fundingMode_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractAddress_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, contractAddress_);
      }
      if (gasPrice_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, gasPrice_);
      }
      if (shouldPinContract_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, shouldPinContract_);
      }
      if (isMigrationAllowed_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isMigrationAllowed_);
      }
      if (codeId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, codeId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(adminAddress_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, adminAddress_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(granterAddress_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, granterAddress_);
      }
      if (fundingMode_ != injective.wasmx.v1.Proposal.FundingMode.Unspecified.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, fundingMode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof injective.wasmx.v1.Events.EventContractRegistered)) {
        return super.equals(obj);
      }
      injective.wasmx.v1.Events.EventContractRegistered other = (injective.wasmx.v1.Events.EventContractRegistered) obj;

      if (!getContractAddress()
          .equals(other.getContractAddress())) return false;
      if (getGasPrice()
          != other.getGasPrice()) return false;
      if (getShouldPinContract()
          != other.getShouldPinContract()) return false;
      if (getIsMigrationAllowed()
          != other.getIsMigrationAllowed()) return false;
      if (getCodeId()
          != other.getCodeId()) return false;
      if (!getAdminAddress()
          .equals(other.getAdminAddress())) return false;
      if (!getGranterAddress()
          .equals(other.getGranterAddress())) return false;
      if (fundingMode_ != other.fundingMode_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTRACT_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getContractAddress().hashCode();
      hash = (37 * hash) + GAS_PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGasPrice());
      hash = (37 * hash) + SHOULD_PIN_CONTRACT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getShouldPinContract());
      hash = (37 * hash) + IS_MIGRATION_ALLOWED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsMigrationAllowed());
      hash = (37 * hash) + CODE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCodeId());
      hash = (37 * hash) + ADMIN_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAdminAddress().hashCode();
      hash = (37 * hash) + GRANTER_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getGranterAddress().hashCode();
      hash = (37 * hash) + FUNDING_MODE_FIELD_NUMBER;
      hash = (53 * hash) + fundingMode_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static injective.wasmx.v1.Events.EventContractRegistered parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.wasmx.v1.Events.EventContractRegistered parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.wasmx.v1.Events.EventContractRegistered parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.wasmx.v1.Events.EventContractRegistered parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.wasmx.v1.Events.EventContractRegistered parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.wasmx.v1.Events.EventContractRegistered parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.wasmx.v1.Events.EventContractRegistered parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static injective.wasmx.v1.Events.EventContractRegistered parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static injective.wasmx.v1.Events.EventContractRegistered parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static injective.wasmx.v1.Events.EventContractRegistered parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static injective.wasmx.v1.Events.EventContractRegistered parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static injective.wasmx.v1.Events.EventContractRegistered parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(injective.wasmx.v1.Events.EventContractRegistered prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code injective.wasmx.v1.EventContractRegistered}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:injective.wasmx.v1.EventContractRegistered)
        injective.wasmx.v1.Events.EventContractRegisteredOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return injective.wasmx.v1.Events.internal_static_injective_wasmx_v1_EventContractRegistered_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return injective.wasmx.v1.Events.internal_static_injective_wasmx_v1_EventContractRegistered_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                injective.wasmx.v1.Events.EventContractRegistered.class, injective.wasmx.v1.Events.EventContractRegistered.Builder.class);
      }

      // Construct using injective.wasmx.v1.Events.EventContractRegistered.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        contractAddress_ = "";
        gasPrice_ = 0L;
        shouldPinContract_ = false;
        isMigrationAllowed_ = false;
        codeId_ = 0L;
        adminAddress_ = "";
        granterAddress_ = "";
        fundingMode_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return injective.wasmx.v1.Events.internal_static_injective_wasmx_v1_EventContractRegistered_descriptor;
      }

      @java.lang.Override
      public injective.wasmx.v1.Events.EventContractRegistered getDefaultInstanceForType() {
        return injective.wasmx.v1.Events.EventContractRegistered.getDefaultInstance();
      }

      @java.lang.Override
      public injective.wasmx.v1.Events.EventContractRegistered build() {
        injective.wasmx.v1.Events.EventContractRegistered result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public injective.wasmx.v1.Events.EventContractRegistered buildPartial() {
        injective.wasmx.v1.Events.EventContractRegistered result = new injective.wasmx.v1.Events.EventContractRegistered(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(injective.wasmx.v1.Events.EventContractRegistered result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.contractAddress_ = contractAddress_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.gasPrice_ = gasPrice_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.shouldPinContract_ = shouldPinContract_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.isMigrationAllowed_ = isMigrationAllowed_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.codeId_ = codeId_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.adminAddress_ = adminAddress_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.granterAddress_ = granterAddress_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.fundingMode_ = fundingMode_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof injective.wasmx.v1.Events.EventContractRegistered) {
          return mergeFrom((injective.wasmx.v1.Events.EventContractRegistered)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(injective.wasmx.v1.Events.EventContractRegistered other) {
        if (other == injective.wasmx.v1.Events.EventContractRegistered.getDefaultInstance()) return this;
        if (!other.getContractAddress().isEmpty()) {
          contractAddress_ = other.contractAddress_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getGasPrice() != 0L) {
          setGasPrice(other.getGasPrice());
        }
        if (other.getShouldPinContract() != false) {
          setShouldPinContract(other.getShouldPinContract());
        }
        if (other.getIsMigrationAllowed() != false) {
          setIsMigrationAllowed(other.getIsMigrationAllowed());
        }
        if (other.getCodeId() != 0L) {
          setCodeId(other.getCodeId());
        }
        if (!other.getAdminAddress().isEmpty()) {
          adminAddress_ = other.adminAddress_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getGranterAddress().isEmpty()) {
          granterAddress_ = other.granterAddress_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.fundingMode_ != 0) {
          setFundingModeValue(other.getFundingModeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                contractAddress_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 24: {
                gasPrice_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 24
              case 32: {
                shouldPinContract_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 32
              case 40: {
                isMigrationAllowed_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 40
              case 48: {
                codeId_ = input.readUInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 48
              case 58: {
                adminAddress_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 58
              case 66: {
                granterAddress_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 66
              case 72: {
                fundingMode_ = input.readEnum();
                bitField0_ |= 0x00000080;
                break;
              } // case 72
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object contractAddress_ = "";
      /**
       * <code>string contract_address = 1;</code>
       * @return The contractAddress.
       */
      public java.lang.String getContractAddress() {
        java.lang.Object ref = contractAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contractAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string contract_address = 1;</code>
       * @return The bytes for contractAddress.
       */
      public com.google.protobuf.ByteString
          getContractAddressBytes() {
        java.lang.Object ref = contractAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contractAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string contract_address = 1;</code>
       * @param value The contractAddress to set.
       * @return This builder for chaining.
       */
      public Builder setContractAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        contractAddress_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string contract_address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearContractAddress() {
        contractAddress_ = getDefaultInstance().getContractAddress();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string contract_address = 1;</code>
       * @param value The bytes for contractAddress to set.
       * @return This builder for chaining.
       */
      public Builder setContractAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        contractAddress_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private long gasPrice_ ;
      /**
       * <code>uint64 gas_price = 3;</code>
       * @return The gasPrice.
       */
      @java.lang.Override
      public long getGasPrice() {
        return gasPrice_;
      }
      /**
       * <code>uint64 gas_price = 3;</code>
       * @param value The gasPrice to set.
       * @return This builder for chaining.
       */
      public Builder setGasPrice(long value) {

        gasPrice_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 gas_price = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGasPrice() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gasPrice_ = 0L;
        onChanged();
        return this;
      }

      private boolean shouldPinContract_ ;
      /**
       * <code>bool should_pin_contract = 4;</code>
       * @return The shouldPinContract.
       */
      @java.lang.Override
      public boolean getShouldPinContract() {
        return shouldPinContract_;
      }
      /**
       * <code>bool should_pin_contract = 4;</code>
       * @param value The shouldPinContract to set.
       * @return This builder for chaining.
       */
      public Builder setShouldPinContract(boolean value) {

        shouldPinContract_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool should_pin_contract = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearShouldPinContract() {
        bitField0_ = (bitField0_ & ~0x00000004);
        shouldPinContract_ = false;
        onChanged();
        return this;
      }

      private boolean isMigrationAllowed_ ;
      /**
       * <code>bool is_migration_allowed = 5;</code>
       * @return The isMigrationAllowed.
       */
      @java.lang.Override
      public boolean getIsMigrationAllowed() {
        return isMigrationAllowed_;
      }
      /**
       * <code>bool is_migration_allowed = 5;</code>
       * @param value The isMigrationAllowed to set.
       * @return This builder for chaining.
       */
      public Builder setIsMigrationAllowed(boolean value) {

        isMigrationAllowed_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_migration_allowed = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsMigrationAllowed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isMigrationAllowed_ = false;
        onChanged();
        return this;
      }

      private long codeId_ ;
      /**
       * <code>uint64 code_id = 6;</code>
       * @return The codeId.
       */
      @java.lang.Override
      public long getCodeId() {
        return codeId_;
      }
      /**
       * <code>uint64 code_id = 6;</code>
       * @param value The codeId to set.
       * @return This builder for chaining.
       */
      public Builder setCodeId(long value) {

        codeId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 code_id = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCodeId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        codeId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object adminAddress_ = "";
      /**
       * <code>string admin_address = 7;</code>
       * @return The adminAddress.
       */
      public java.lang.String getAdminAddress() {
        java.lang.Object ref = adminAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          adminAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string admin_address = 7;</code>
       * @return The bytes for adminAddress.
       */
      public com.google.protobuf.ByteString
          getAdminAddressBytes() {
        java.lang.Object ref = adminAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          adminAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string admin_address = 7;</code>
       * @param value The adminAddress to set.
       * @return This builder for chaining.
       */
      public Builder setAdminAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        adminAddress_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string admin_address = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAdminAddress() {
        adminAddress_ = getDefaultInstance().getAdminAddress();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string admin_address = 7;</code>
       * @param value The bytes for adminAddress to set.
       * @return This builder for chaining.
       */
      public Builder setAdminAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        adminAddress_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object granterAddress_ = "";
      /**
       * <code>string granter_address = 8;</code>
       * @return The granterAddress.
       */
      public java.lang.String getGranterAddress() {
        java.lang.Object ref = granterAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          granterAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string granter_address = 8;</code>
       * @return The bytes for granterAddress.
       */
      public com.google.protobuf.ByteString
          getGranterAddressBytes() {
        java.lang.Object ref = granterAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          granterAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string granter_address = 8;</code>
       * @param value The granterAddress to set.
       * @return This builder for chaining.
       */
      public Builder setGranterAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        granterAddress_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string granter_address = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearGranterAddress() {
        granterAddress_ = getDefaultInstance().getGranterAddress();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string granter_address = 8;</code>
       * @param value The bytes for granterAddress to set.
       * @return This builder for chaining.
       */
      public Builder setGranterAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        granterAddress_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private int fundingMode_ = 0;
      /**
       * <code>.injective.wasmx.v1.FundingMode funding_mode = 9;</code>
       * @return The enum numeric value on the wire for fundingMode.
       */
      @java.lang.Override public int getFundingModeValue() {
        return fundingMode_;
      }
      /**
       * <code>.injective.wasmx.v1.FundingMode funding_mode = 9;</code>
       * @param value The enum numeric value on the wire for fundingMode to set.
       * @return This builder for chaining.
       */
      public Builder setFundingModeValue(int value) {
        fundingMode_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>.injective.wasmx.v1.FundingMode funding_mode = 9;</code>
       * @return The fundingMode.
       */
      @java.lang.Override
      public injective.wasmx.v1.Proposal.FundingMode getFundingMode() {
        injective.wasmx.v1.Proposal.FundingMode result = injective.wasmx.v1.Proposal.FundingMode.forNumber(fundingMode_);
        return result == null ? injective.wasmx.v1.Proposal.FundingMode.UNRECOGNIZED : result;
      }
      /**
       * <code>.injective.wasmx.v1.FundingMode funding_mode = 9;</code>
       * @param value The fundingMode to set.
       * @return This builder for chaining.
       */
      public Builder setFundingMode(injective.wasmx.v1.Proposal.FundingMode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        fundingMode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.injective.wasmx.v1.FundingMode funding_mode = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearFundingMode() {
        bitField0_ = (bitField0_ & ~0x00000080);
        fundingMode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:injective.wasmx.v1.EventContractRegistered)
    }

    // @@protoc_insertion_point(class_scope:injective.wasmx.v1.EventContractRegistered)
    private static final injective.wasmx.v1.Events.EventContractRegistered DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new injective.wasmx.v1.Events.EventContractRegistered();
    }

    public static injective.wasmx.v1.Events.EventContractRegistered getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EventContractRegistered>
        PARSER = new com.google.protobuf.AbstractParser<EventContractRegistered>() {
      @java.lang.Override
      public EventContractRegistered parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EventContractRegistered> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EventContractRegistered> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public injective.wasmx.v1.Events.EventContractRegistered getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EventContractDeregisteredOrBuilder extends
      // @@protoc_insertion_point(interface_extends:injective.wasmx.v1.EventContractDeregistered)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string contract_address = 1;</code>
     * @return The contractAddress.
     */
    java.lang.String getContractAddress();
    /**
     * <code>string contract_address = 1;</code>
     * @return The bytes for contractAddress.
     */
    com.google.protobuf.ByteString
        getContractAddressBytes();
  }
  /**
   * Protobuf type {@code injective.wasmx.v1.EventContractDeregistered}
   */
  public static final class EventContractDeregistered extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:injective.wasmx.v1.EventContractDeregistered)
      EventContractDeregisteredOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EventContractDeregistered.newBuilder() to construct.
    private EventContractDeregistered(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EventContractDeregistered() {
      contractAddress_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EventContractDeregistered();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return injective.wasmx.v1.Events.internal_static_injective_wasmx_v1_EventContractDeregistered_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return injective.wasmx.v1.Events.internal_static_injective_wasmx_v1_EventContractDeregistered_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              injective.wasmx.v1.Events.EventContractDeregistered.class, injective.wasmx.v1.Events.EventContractDeregistered.Builder.class);
    }

    public static final int CONTRACT_ADDRESS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object contractAddress_ = "";
    /**
     * <code>string contract_address = 1;</code>
     * @return The contractAddress.
     */
    @java.lang.Override
    public java.lang.String getContractAddress() {
      java.lang.Object ref = contractAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractAddress_ = s;
        return s;
      }
    }
    /**
     * <code>string contract_address = 1;</code>
     * @return The bytes for contractAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContractAddressBytes() {
      java.lang.Object ref = contractAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractAddress_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contractAddress_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractAddress_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, contractAddress_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof injective.wasmx.v1.Events.EventContractDeregistered)) {
        return super.equals(obj);
      }
      injective.wasmx.v1.Events.EventContractDeregistered other = (injective.wasmx.v1.Events.EventContractDeregistered) obj;

      if (!getContractAddress()
          .equals(other.getContractAddress())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTRACT_ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getContractAddress().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static injective.wasmx.v1.Events.EventContractDeregistered parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.wasmx.v1.Events.EventContractDeregistered parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.wasmx.v1.Events.EventContractDeregistered parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.wasmx.v1.Events.EventContractDeregistered parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.wasmx.v1.Events.EventContractDeregistered parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.wasmx.v1.Events.EventContractDeregistered parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.wasmx.v1.Events.EventContractDeregistered parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static injective.wasmx.v1.Events.EventContractDeregistered parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static injective.wasmx.v1.Events.EventContractDeregistered parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static injective.wasmx.v1.Events.EventContractDeregistered parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static injective.wasmx.v1.Events.EventContractDeregistered parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static injective.wasmx.v1.Events.EventContractDeregistered parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(injective.wasmx.v1.Events.EventContractDeregistered prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code injective.wasmx.v1.EventContractDeregistered}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:injective.wasmx.v1.EventContractDeregistered)
        injective.wasmx.v1.Events.EventContractDeregisteredOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return injective.wasmx.v1.Events.internal_static_injective_wasmx_v1_EventContractDeregistered_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return injective.wasmx.v1.Events.internal_static_injective_wasmx_v1_EventContractDeregistered_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                injective.wasmx.v1.Events.EventContractDeregistered.class, injective.wasmx.v1.Events.EventContractDeregistered.Builder.class);
      }

      // Construct using injective.wasmx.v1.Events.EventContractDeregistered.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        contractAddress_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return injective.wasmx.v1.Events.internal_static_injective_wasmx_v1_EventContractDeregistered_descriptor;
      }

      @java.lang.Override
      public injective.wasmx.v1.Events.EventContractDeregistered getDefaultInstanceForType() {
        return injective.wasmx.v1.Events.EventContractDeregistered.getDefaultInstance();
      }

      @java.lang.Override
      public injective.wasmx.v1.Events.EventContractDeregistered build() {
        injective.wasmx.v1.Events.EventContractDeregistered result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public injective.wasmx.v1.Events.EventContractDeregistered buildPartial() {
        injective.wasmx.v1.Events.EventContractDeregistered result = new injective.wasmx.v1.Events.EventContractDeregistered(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(injective.wasmx.v1.Events.EventContractDeregistered result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.contractAddress_ = contractAddress_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof injective.wasmx.v1.Events.EventContractDeregistered) {
          return mergeFrom((injective.wasmx.v1.Events.EventContractDeregistered)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(injective.wasmx.v1.Events.EventContractDeregistered other) {
        if (other == injective.wasmx.v1.Events.EventContractDeregistered.getDefaultInstance()) return this;
        if (!other.getContractAddress().isEmpty()) {
          contractAddress_ = other.contractAddress_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                contractAddress_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object contractAddress_ = "";
      /**
       * <code>string contract_address = 1;</code>
       * @return The contractAddress.
       */
      public java.lang.String getContractAddress() {
        java.lang.Object ref = contractAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contractAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string contract_address = 1;</code>
       * @return The bytes for contractAddress.
       */
      public com.google.protobuf.ByteString
          getContractAddressBytes() {
        java.lang.Object ref = contractAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contractAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string contract_address = 1;</code>
       * @param value The contractAddress to set.
       * @return This builder for chaining.
       */
      public Builder setContractAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        contractAddress_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string contract_address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearContractAddress() {
        contractAddress_ = getDefaultInstance().getContractAddress();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string contract_address = 1;</code>
       * @param value The bytes for contractAddress to set.
       * @return This builder for chaining.
       */
      public Builder setContractAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        contractAddress_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:injective.wasmx.v1.EventContractDeregistered)
    }

    // @@protoc_insertion_point(class_scope:injective.wasmx.v1.EventContractDeregistered)
    private static final injective.wasmx.v1.Events.EventContractDeregistered DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new injective.wasmx.v1.Events.EventContractDeregistered();
    }

    public static injective.wasmx.v1.Events.EventContractDeregistered getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EventContractDeregistered>
        PARSER = new com.google.protobuf.AbstractParser<EventContractDeregistered>() {
      @java.lang.Override
      public EventContractDeregistered parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EventContractDeregistered> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EventContractDeregistered> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public injective.wasmx.v1.Events.EventContractDeregistered getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_injective_wasmx_v1_EventContractExecution_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_injective_wasmx_v1_EventContractExecution_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_injective_wasmx_v1_EventContractRegistered_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_injective_wasmx_v1_EventContractRegistered_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_injective_wasmx_v1_EventContractDeregistered_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_injective_wasmx_v1_EventContractDeregistered_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037injective/wasmx/v1/events.proto\022\022injec" +
      "tive.wasmx.v1\032\036injective/wasmx/v1/wasmx." +
      "proto\032!injective/wasmx/v1/proposal.proto" +
      "\032\024gogoproto/gogo.proto\"r\n\026EventContractE" +
      "xecution\022\030\n\020contract_address\030\001 \001(\t\022\020\n\010re" +
      "sponse\030\002 \001(\014\022\023\n\013other_error\030\003 \001(\t\022\027\n\017exe" +
      "cution_error\030\004 \001(\t\"\371\001\n\027EventContractRegi" +
      "stered\022\030\n\020contract_address\030\001 \001(\t\022\021\n\tgas_" +
      "price\030\003 \001(\004\022\033\n\023should_pin_contract\030\004 \001(\010" +
      "\022\034\n\024is_migration_allowed\030\005 \001(\010\022\017\n\007code_i" +
      "d\030\006 \001(\004\022\025\n\radmin_address\030\007 \001(\t\022\027\n\017grante" +
      "r_address\030\010 \001(\t\0225\n\014funding_mode\030\t \001(\0162\037." +
      "injective.wasmx.v1.FundingMode\"5\n\031EventC" +
      "ontractDeregistered\022\030\n\020contract_address\030" +
      "\001 \001(\tBMZKgithub.com/InjectiveLabs/inject" +
      "ive-core/injective-chain/modules/wasmx/t" +
      "ypesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          injective.wasmx.v1.Wasmx.getDescriptor(),
          injective.wasmx.v1.Proposal.getDescriptor(),
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_injective_wasmx_v1_EventContractExecution_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_injective_wasmx_v1_EventContractExecution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_injective_wasmx_v1_EventContractExecution_descriptor,
        new java.lang.String[] { "ContractAddress", "Response", "OtherError", "ExecutionError", });
    internal_static_injective_wasmx_v1_EventContractRegistered_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_injective_wasmx_v1_EventContractRegistered_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_injective_wasmx_v1_EventContractRegistered_descriptor,
        new java.lang.String[] { "ContractAddress", "GasPrice", "ShouldPinContract", "IsMigrationAllowed", "CodeId", "AdminAddress", "GranterAddress", "FundingMode", });
    internal_static_injective_wasmx_v1_EventContractDeregistered_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_injective_wasmx_v1_EventContractDeregistered_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_injective_wasmx_v1_EventContractDeregistered_descriptor,
        new java.lang.String[] { "ContractAddress", });
    injective.wasmx.v1.Wasmx.getDescriptor();
    injective.wasmx.v1.Proposal.getDescriptor();
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
