// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: injective/wasmx/v1/genesis.proto

package injective.wasmx.v1;

public final class Genesis {
  private Genesis() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RegisteredContractWithAddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:injective.wasmx.v1.RegisteredContractWithAddress)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string address = 1;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 1;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>.injective.wasmx.v1.RegisteredContract registered_contract = 2;</code>
     * @return Whether the registeredContract field is set.
     */
    boolean hasRegisteredContract();
    /**
     * <code>.injective.wasmx.v1.RegisteredContract registered_contract = 2;</code>
     * @return The registeredContract.
     */
    injective.wasmx.v1.Wasmx.RegisteredContract getRegisteredContract();
    /**
     * <code>.injective.wasmx.v1.RegisteredContract registered_contract = 2;</code>
     */
    injective.wasmx.v1.Wasmx.RegisteredContractOrBuilder getRegisteredContractOrBuilder();
  }
  /**
   * Protobuf type {@code injective.wasmx.v1.RegisteredContractWithAddress}
   */
  public static final class RegisteredContractWithAddress extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:injective.wasmx.v1.RegisteredContractWithAddress)
      RegisteredContractWithAddressOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RegisteredContractWithAddress.newBuilder() to construct.
    private RegisteredContractWithAddress(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RegisteredContractWithAddress() {
      address_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RegisteredContractWithAddress();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return injective.wasmx.v1.Genesis.internal_static_injective_wasmx_v1_RegisteredContractWithAddress_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return injective.wasmx.v1.Genesis.internal_static_injective_wasmx_v1_RegisteredContractWithAddress_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              injective.wasmx.v1.Genesis.RegisteredContractWithAddress.class, injective.wasmx.v1.Genesis.RegisteredContractWithAddress.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object address_ = "";
    /**
     * <code>string address = 1;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 1;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REGISTERED_CONTRACT_FIELD_NUMBER = 2;
    private injective.wasmx.v1.Wasmx.RegisteredContract registeredContract_;
    /**
     * <code>.injective.wasmx.v1.RegisteredContract registered_contract = 2;</code>
     * @return Whether the registeredContract field is set.
     */
    @java.lang.Override
    public boolean hasRegisteredContract() {
      return registeredContract_ != null;
    }
    /**
     * <code>.injective.wasmx.v1.RegisteredContract registered_contract = 2;</code>
     * @return The registeredContract.
     */
    @java.lang.Override
    public injective.wasmx.v1.Wasmx.RegisteredContract getRegisteredContract() {
      return registeredContract_ == null ? injective.wasmx.v1.Wasmx.RegisteredContract.getDefaultInstance() : registeredContract_;
    }
    /**
     * <code>.injective.wasmx.v1.RegisteredContract registered_contract = 2;</code>
     */
    @java.lang.Override
    public injective.wasmx.v1.Wasmx.RegisteredContractOrBuilder getRegisteredContractOrBuilder() {
      return registeredContract_ == null ? injective.wasmx.v1.Wasmx.RegisteredContract.getDefaultInstance() : registeredContract_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
      }
      if (registeredContract_ != null) {
        output.writeMessage(2, getRegisteredContract());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
      }
      if (registeredContract_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRegisteredContract());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof injective.wasmx.v1.Genesis.RegisteredContractWithAddress)) {
        return super.equals(obj);
      }
      injective.wasmx.v1.Genesis.RegisteredContractWithAddress other = (injective.wasmx.v1.Genesis.RegisteredContractWithAddress) obj;

      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (hasRegisteredContract() != other.hasRegisteredContract()) return false;
      if (hasRegisteredContract()) {
        if (!getRegisteredContract()
            .equals(other.getRegisteredContract())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      if (hasRegisteredContract()) {
        hash = (37 * hash) + REGISTERED_CONTRACT_FIELD_NUMBER;
        hash = (53 * hash) + getRegisteredContract().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static injective.wasmx.v1.Genesis.RegisteredContractWithAddress parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.wasmx.v1.Genesis.RegisteredContractWithAddress parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.wasmx.v1.Genesis.RegisteredContractWithAddress parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.wasmx.v1.Genesis.RegisteredContractWithAddress parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.wasmx.v1.Genesis.RegisteredContractWithAddress parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.wasmx.v1.Genesis.RegisteredContractWithAddress parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.wasmx.v1.Genesis.RegisteredContractWithAddress parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static injective.wasmx.v1.Genesis.RegisteredContractWithAddress parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static injective.wasmx.v1.Genesis.RegisteredContractWithAddress parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static injective.wasmx.v1.Genesis.RegisteredContractWithAddress parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static injective.wasmx.v1.Genesis.RegisteredContractWithAddress parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static injective.wasmx.v1.Genesis.RegisteredContractWithAddress parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(injective.wasmx.v1.Genesis.RegisteredContractWithAddress prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code injective.wasmx.v1.RegisteredContractWithAddress}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:injective.wasmx.v1.RegisteredContractWithAddress)
        injective.wasmx.v1.Genesis.RegisteredContractWithAddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return injective.wasmx.v1.Genesis.internal_static_injective_wasmx_v1_RegisteredContractWithAddress_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return injective.wasmx.v1.Genesis.internal_static_injective_wasmx_v1_RegisteredContractWithAddress_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                injective.wasmx.v1.Genesis.RegisteredContractWithAddress.class, injective.wasmx.v1.Genesis.RegisteredContractWithAddress.Builder.class);
      }

      // Construct using injective.wasmx.v1.Genesis.RegisteredContractWithAddress.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        address_ = "";
        registeredContract_ = null;
        if (registeredContractBuilder_ != null) {
          registeredContractBuilder_.dispose();
          registeredContractBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return injective.wasmx.v1.Genesis.internal_static_injective_wasmx_v1_RegisteredContractWithAddress_descriptor;
      }

      @java.lang.Override
      public injective.wasmx.v1.Genesis.RegisteredContractWithAddress getDefaultInstanceForType() {
        return injective.wasmx.v1.Genesis.RegisteredContractWithAddress.getDefaultInstance();
      }

      @java.lang.Override
      public injective.wasmx.v1.Genesis.RegisteredContractWithAddress build() {
        injective.wasmx.v1.Genesis.RegisteredContractWithAddress result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public injective.wasmx.v1.Genesis.RegisteredContractWithAddress buildPartial() {
        injective.wasmx.v1.Genesis.RegisteredContractWithAddress result = new injective.wasmx.v1.Genesis.RegisteredContractWithAddress(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(injective.wasmx.v1.Genesis.RegisteredContractWithAddress result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.address_ = address_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.registeredContract_ = registeredContractBuilder_ == null
              ? registeredContract_
              : registeredContractBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof injective.wasmx.v1.Genesis.RegisteredContractWithAddress) {
          return mergeFrom((injective.wasmx.v1.Genesis.RegisteredContractWithAddress)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(injective.wasmx.v1.Genesis.RegisteredContractWithAddress other) {
        if (other == injective.wasmx.v1.Genesis.RegisteredContractWithAddress.getDefaultInstance()) return this;
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasRegisteredContract()) {
          mergeRegisteredContract(other.getRegisteredContract());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                address_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getRegisteredContractFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 1;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 1;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 1;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        address_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        address_ = getDefaultInstance().getAddress();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string address = 1;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        address_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private injective.wasmx.v1.Wasmx.RegisteredContract registeredContract_;
      private com.google.protobuf.SingleFieldBuilderV3<
          injective.wasmx.v1.Wasmx.RegisteredContract, injective.wasmx.v1.Wasmx.RegisteredContract.Builder, injective.wasmx.v1.Wasmx.RegisteredContractOrBuilder> registeredContractBuilder_;
      /**
       * <code>.injective.wasmx.v1.RegisteredContract registered_contract = 2;</code>
       * @return Whether the registeredContract field is set.
       */
      public boolean hasRegisteredContract() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.injective.wasmx.v1.RegisteredContract registered_contract = 2;</code>
       * @return The registeredContract.
       */
      public injective.wasmx.v1.Wasmx.RegisteredContract getRegisteredContract() {
        if (registeredContractBuilder_ == null) {
          return registeredContract_ == null ? injective.wasmx.v1.Wasmx.RegisteredContract.getDefaultInstance() : registeredContract_;
        } else {
          return registeredContractBuilder_.getMessage();
        }
      }
      /**
       * <code>.injective.wasmx.v1.RegisteredContract registered_contract = 2;</code>
       */
      public Builder setRegisteredContract(injective.wasmx.v1.Wasmx.RegisteredContract value) {
        if (registeredContractBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          registeredContract_ = value;
        } else {
          registeredContractBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.injective.wasmx.v1.RegisteredContract registered_contract = 2;</code>
       */
      public Builder setRegisteredContract(
          injective.wasmx.v1.Wasmx.RegisteredContract.Builder builderForValue) {
        if (registeredContractBuilder_ == null) {
          registeredContract_ = builderForValue.build();
        } else {
          registeredContractBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.injective.wasmx.v1.RegisteredContract registered_contract = 2;</code>
       */
      public Builder mergeRegisteredContract(injective.wasmx.v1.Wasmx.RegisteredContract value) {
        if (registeredContractBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            registeredContract_ != null &&
            registeredContract_ != injective.wasmx.v1.Wasmx.RegisteredContract.getDefaultInstance()) {
            getRegisteredContractBuilder().mergeFrom(value);
          } else {
            registeredContract_ = value;
          }
        } else {
          registeredContractBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.injective.wasmx.v1.RegisteredContract registered_contract = 2;</code>
       */
      public Builder clearRegisteredContract() {
        bitField0_ = (bitField0_ & ~0x00000002);
        registeredContract_ = null;
        if (registeredContractBuilder_ != null) {
          registeredContractBuilder_.dispose();
          registeredContractBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.injective.wasmx.v1.RegisteredContract registered_contract = 2;</code>
       */
      public injective.wasmx.v1.Wasmx.RegisteredContract.Builder getRegisteredContractBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRegisteredContractFieldBuilder().getBuilder();
      }
      /**
       * <code>.injective.wasmx.v1.RegisteredContract registered_contract = 2;</code>
       */
      public injective.wasmx.v1.Wasmx.RegisteredContractOrBuilder getRegisteredContractOrBuilder() {
        if (registeredContractBuilder_ != null) {
          return registeredContractBuilder_.getMessageOrBuilder();
        } else {
          return registeredContract_ == null ?
              injective.wasmx.v1.Wasmx.RegisteredContract.getDefaultInstance() : registeredContract_;
        }
      }
      /**
       * <code>.injective.wasmx.v1.RegisteredContract registered_contract = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          injective.wasmx.v1.Wasmx.RegisteredContract, injective.wasmx.v1.Wasmx.RegisteredContract.Builder, injective.wasmx.v1.Wasmx.RegisteredContractOrBuilder> 
          getRegisteredContractFieldBuilder() {
        if (registeredContractBuilder_ == null) {
          registeredContractBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              injective.wasmx.v1.Wasmx.RegisteredContract, injective.wasmx.v1.Wasmx.RegisteredContract.Builder, injective.wasmx.v1.Wasmx.RegisteredContractOrBuilder>(
                  getRegisteredContract(),
                  getParentForChildren(),
                  isClean());
          registeredContract_ = null;
        }
        return registeredContractBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:injective.wasmx.v1.RegisteredContractWithAddress)
    }

    // @@protoc_insertion_point(class_scope:injective.wasmx.v1.RegisteredContractWithAddress)
    private static final injective.wasmx.v1.Genesis.RegisteredContractWithAddress DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new injective.wasmx.v1.Genesis.RegisteredContractWithAddress();
    }

    public static injective.wasmx.v1.Genesis.RegisteredContractWithAddress getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RegisteredContractWithAddress>
        PARSER = new com.google.protobuf.AbstractParser<RegisteredContractWithAddress>() {
      @java.lang.Override
      public RegisteredContractWithAddress parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RegisteredContractWithAddress> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RegisteredContractWithAddress> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public injective.wasmx.v1.Genesis.RegisteredContractWithAddress getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GenesisStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:injective.wasmx.v1.GenesisState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * params defines all the parameters of related to wasmx.
     * </pre>
     *
     * <code>.injective.wasmx.v1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     * @return Whether the params field is set.
     */
    boolean hasParams();
    /**
     * <pre>
     * params defines all the parameters of related to wasmx.
     * </pre>
     *
     * <code>.injective.wasmx.v1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     * @return The params.
     */
    injective.wasmx.v1.Wasmx.Params getParams();
    /**
     * <pre>
     * params defines all the parameters of related to wasmx.
     * </pre>
     *
     * <code>.injective.wasmx.v1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     */
    injective.wasmx.v1.Wasmx.ParamsOrBuilder getParamsOrBuilder();

    /**
     * <pre>
     * registered_contracts is an array containing the genesis registered
     * contracts
     * </pre>
     *
     * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
     */
    java.util.List<injective.wasmx.v1.Genesis.RegisteredContractWithAddress> 
        getRegisteredContractsList();
    /**
     * <pre>
     * registered_contracts is an array containing the genesis registered
     * contracts
     * </pre>
     *
     * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
     */
    injective.wasmx.v1.Genesis.RegisteredContractWithAddress getRegisteredContracts(int index);
    /**
     * <pre>
     * registered_contracts is an array containing the genesis registered
     * contracts
     * </pre>
     *
     * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
     */
    int getRegisteredContractsCount();
    /**
     * <pre>
     * registered_contracts is an array containing the genesis registered
     * contracts
     * </pre>
     *
     * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
     */
    java.util.List<? extends injective.wasmx.v1.Genesis.RegisteredContractWithAddressOrBuilder> 
        getRegisteredContractsOrBuilderList();
    /**
     * <pre>
     * registered_contracts is an array containing the genesis registered
     * contracts
     * </pre>
     *
     * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
     */
    injective.wasmx.v1.Genesis.RegisteredContractWithAddressOrBuilder getRegisteredContractsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * GenesisState defines the wasmx module's genesis state.
   * </pre>
   *
   * Protobuf type {@code injective.wasmx.v1.GenesisState}
   */
  public static final class GenesisState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:injective.wasmx.v1.GenesisState)
      GenesisStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GenesisState.newBuilder() to construct.
    private GenesisState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenesisState() {
      registeredContracts_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GenesisState();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return injective.wasmx.v1.Genesis.internal_static_injective_wasmx_v1_GenesisState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return injective.wasmx.v1.Genesis.internal_static_injective_wasmx_v1_GenesisState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              injective.wasmx.v1.Genesis.GenesisState.class, injective.wasmx.v1.Genesis.GenesisState.Builder.class);
    }

    public static final int PARAMS_FIELD_NUMBER = 1;
    private injective.wasmx.v1.Wasmx.Params params_;
    /**
     * <pre>
     * params defines all the parameters of related to wasmx.
     * </pre>
     *
     * <code>.injective.wasmx.v1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     * @return Whether the params field is set.
     */
    @java.lang.Override
    public boolean hasParams() {
      return params_ != null;
    }
    /**
     * <pre>
     * params defines all the parameters of related to wasmx.
     * </pre>
     *
     * <code>.injective.wasmx.v1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     * @return The params.
     */
    @java.lang.Override
    public injective.wasmx.v1.Wasmx.Params getParams() {
      return params_ == null ? injective.wasmx.v1.Wasmx.Params.getDefaultInstance() : params_;
    }
    /**
     * <pre>
     * params defines all the parameters of related to wasmx.
     * </pre>
     *
     * <code>.injective.wasmx.v1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public injective.wasmx.v1.Wasmx.ParamsOrBuilder getParamsOrBuilder() {
      return params_ == null ? injective.wasmx.v1.Wasmx.Params.getDefaultInstance() : params_;
    }

    public static final int REGISTERED_CONTRACTS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<injective.wasmx.v1.Genesis.RegisteredContractWithAddress> registeredContracts_;
    /**
     * <pre>
     * registered_contracts is an array containing the genesis registered
     * contracts
     * </pre>
     *
     * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public java.util.List<injective.wasmx.v1.Genesis.RegisteredContractWithAddress> getRegisteredContractsList() {
      return registeredContracts_;
    }
    /**
     * <pre>
     * registered_contracts is an array containing the genesis registered
     * contracts
     * </pre>
     *
     * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public java.util.List<? extends injective.wasmx.v1.Genesis.RegisteredContractWithAddressOrBuilder> 
        getRegisteredContractsOrBuilderList() {
      return registeredContracts_;
    }
    /**
     * <pre>
     * registered_contracts is an array containing the genesis registered
     * contracts
     * </pre>
     *
     * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public int getRegisteredContractsCount() {
      return registeredContracts_.size();
    }
    /**
     * <pre>
     * registered_contracts is an array containing the genesis registered
     * contracts
     * </pre>
     *
     * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public injective.wasmx.v1.Genesis.RegisteredContractWithAddress getRegisteredContracts(int index) {
      return registeredContracts_.get(index);
    }
    /**
     * <pre>
     * registered_contracts is an array containing the genesis registered
     * contracts
     * </pre>
     *
     * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public injective.wasmx.v1.Genesis.RegisteredContractWithAddressOrBuilder getRegisteredContractsOrBuilder(
        int index) {
      return registeredContracts_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (params_ != null) {
        output.writeMessage(1, getParams());
      }
      for (int i = 0; i < registeredContracts_.size(); i++) {
        output.writeMessage(2, registeredContracts_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (params_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getParams());
      }
      for (int i = 0; i < registeredContracts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, registeredContracts_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof injective.wasmx.v1.Genesis.GenesisState)) {
        return super.equals(obj);
      }
      injective.wasmx.v1.Genesis.GenesisState other = (injective.wasmx.v1.Genesis.GenesisState) obj;

      if (hasParams() != other.hasParams()) return false;
      if (hasParams()) {
        if (!getParams()
            .equals(other.getParams())) return false;
      }
      if (!getRegisteredContractsList()
          .equals(other.getRegisteredContractsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasParams()) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParams().hashCode();
      }
      if (getRegisteredContractsCount() > 0) {
        hash = (37 * hash) + REGISTERED_CONTRACTS_FIELD_NUMBER;
        hash = (53 * hash) + getRegisteredContractsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static injective.wasmx.v1.Genesis.GenesisState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.wasmx.v1.Genesis.GenesisState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.wasmx.v1.Genesis.GenesisState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.wasmx.v1.Genesis.GenesisState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.wasmx.v1.Genesis.GenesisState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.wasmx.v1.Genesis.GenesisState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.wasmx.v1.Genesis.GenesisState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static injective.wasmx.v1.Genesis.GenesisState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static injective.wasmx.v1.Genesis.GenesisState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static injective.wasmx.v1.Genesis.GenesisState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static injective.wasmx.v1.Genesis.GenesisState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static injective.wasmx.v1.Genesis.GenesisState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(injective.wasmx.v1.Genesis.GenesisState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * GenesisState defines the wasmx module's genesis state.
     * </pre>
     *
     * Protobuf type {@code injective.wasmx.v1.GenesisState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:injective.wasmx.v1.GenesisState)
        injective.wasmx.v1.Genesis.GenesisStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return injective.wasmx.v1.Genesis.internal_static_injective_wasmx_v1_GenesisState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return injective.wasmx.v1.Genesis.internal_static_injective_wasmx_v1_GenesisState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                injective.wasmx.v1.Genesis.GenesisState.class, injective.wasmx.v1.Genesis.GenesisState.Builder.class);
      }

      // Construct using injective.wasmx.v1.Genesis.GenesisState.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        params_ = null;
        if (paramsBuilder_ != null) {
          paramsBuilder_.dispose();
          paramsBuilder_ = null;
        }
        if (registeredContractsBuilder_ == null) {
          registeredContracts_ = java.util.Collections.emptyList();
        } else {
          registeredContracts_ = null;
          registeredContractsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return injective.wasmx.v1.Genesis.internal_static_injective_wasmx_v1_GenesisState_descriptor;
      }

      @java.lang.Override
      public injective.wasmx.v1.Genesis.GenesisState getDefaultInstanceForType() {
        return injective.wasmx.v1.Genesis.GenesisState.getDefaultInstance();
      }

      @java.lang.Override
      public injective.wasmx.v1.Genesis.GenesisState build() {
        injective.wasmx.v1.Genesis.GenesisState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public injective.wasmx.v1.Genesis.GenesisState buildPartial() {
        injective.wasmx.v1.Genesis.GenesisState result = new injective.wasmx.v1.Genesis.GenesisState(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(injective.wasmx.v1.Genesis.GenesisState result) {
        if (registeredContractsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            registeredContracts_ = java.util.Collections.unmodifiableList(registeredContracts_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.registeredContracts_ = registeredContracts_;
        } else {
          result.registeredContracts_ = registeredContractsBuilder_.build();
        }
      }

      private void buildPartial0(injective.wasmx.v1.Genesis.GenesisState result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.params_ = paramsBuilder_ == null
              ? params_
              : paramsBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof injective.wasmx.v1.Genesis.GenesisState) {
          return mergeFrom((injective.wasmx.v1.Genesis.GenesisState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(injective.wasmx.v1.Genesis.GenesisState other) {
        if (other == injective.wasmx.v1.Genesis.GenesisState.getDefaultInstance()) return this;
        if (other.hasParams()) {
          mergeParams(other.getParams());
        }
        if (registeredContractsBuilder_ == null) {
          if (!other.registeredContracts_.isEmpty()) {
            if (registeredContracts_.isEmpty()) {
              registeredContracts_ = other.registeredContracts_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRegisteredContractsIsMutable();
              registeredContracts_.addAll(other.registeredContracts_);
            }
            onChanged();
          }
        } else {
          if (!other.registeredContracts_.isEmpty()) {
            if (registeredContractsBuilder_.isEmpty()) {
              registeredContractsBuilder_.dispose();
              registeredContractsBuilder_ = null;
              registeredContracts_ = other.registeredContracts_;
              bitField0_ = (bitField0_ & ~0x00000002);
              registeredContractsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRegisteredContractsFieldBuilder() : null;
            } else {
              registeredContractsBuilder_.addAllMessages(other.registeredContracts_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getParamsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                injective.wasmx.v1.Genesis.RegisteredContractWithAddress m =
                    input.readMessage(
                        injective.wasmx.v1.Genesis.RegisteredContractWithAddress.parser(),
                        extensionRegistry);
                if (registeredContractsBuilder_ == null) {
                  ensureRegisteredContractsIsMutable();
                  registeredContracts_.add(m);
                } else {
                  registeredContractsBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private injective.wasmx.v1.Wasmx.Params params_;
      private com.google.protobuf.SingleFieldBuilderV3<
          injective.wasmx.v1.Wasmx.Params, injective.wasmx.v1.Wasmx.Params.Builder, injective.wasmx.v1.Wasmx.ParamsOrBuilder> paramsBuilder_;
      /**
       * <pre>
       * params defines all the parameters of related to wasmx.
       * </pre>
       *
       * <code>.injective.wasmx.v1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       * @return Whether the params field is set.
       */
      public boolean hasParams() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * params defines all the parameters of related to wasmx.
       * </pre>
       *
       * <code>.injective.wasmx.v1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       * @return The params.
       */
      public injective.wasmx.v1.Wasmx.Params getParams() {
        if (paramsBuilder_ == null) {
          return params_ == null ? injective.wasmx.v1.Wasmx.Params.getDefaultInstance() : params_;
        } else {
          return paramsBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * params defines all the parameters of related to wasmx.
       * </pre>
       *
       * <code>.injective.wasmx.v1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setParams(injective.wasmx.v1.Wasmx.Params value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          params_ = value;
        } else {
          paramsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * params defines all the parameters of related to wasmx.
       * </pre>
       *
       * <code>.injective.wasmx.v1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setParams(
          injective.wasmx.v1.Wasmx.Params.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          params_ = builderForValue.build();
        } else {
          paramsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * params defines all the parameters of related to wasmx.
       * </pre>
       *
       * <code>.injective.wasmx.v1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder mergeParams(injective.wasmx.v1.Wasmx.Params value) {
        if (paramsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            params_ != null &&
            params_ != injective.wasmx.v1.Wasmx.Params.getDefaultInstance()) {
            getParamsBuilder().mergeFrom(value);
          } else {
            params_ = value;
          }
        } else {
          paramsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * params defines all the parameters of related to wasmx.
       * </pre>
       *
       * <code>.injective.wasmx.v1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearParams() {
        bitField0_ = (bitField0_ & ~0x00000001);
        params_ = null;
        if (paramsBuilder_ != null) {
          paramsBuilder_.dispose();
          paramsBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * params defines all the parameters of related to wasmx.
       * </pre>
       *
       * <code>.injective.wasmx.v1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       */
      public injective.wasmx.v1.Wasmx.Params.Builder getParamsBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getParamsFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * params defines all the parameters of related to wasmx.
       * </pre>
       *
       * <code>.injective.wasmx.v1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       */
      public injective.wasmx.v1.Wasmx.ParamsOrBuilder getParamsOrBuilder() {
        if (paramsBuilder_ != null) {
          return paramsBuilder_.getMessageOrBuilder();
        } else {
          return params_ == null ?
              injective.wasmx.v1.Wasmx.Params.getDefaultInstance() : params_;
        }
      }
      /**
       * <pre>
       * params defines all the parameters of related to wasmx.
       * </pre>
       *
       * <code>.injective.wasmx.v1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          injective.wasmx.v1.Wasmx.Params, injective.wasmx.v1.Wasmx.Params.Builder, injective.wasmx.v1.Wasmx.ParamsOrBuilder> 
          getParamsFieldBuilder() {
        if (paramsBuilder_ == null) {
          paramsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              injective.wasmx.v1.Wasmx.Params, injective.wasmx.v1.Wasmx.Params.Builder, injective.wasmx.v1.Wasmx.ParamsOrBuilder>(
                  getParams(),
                  getParentForChildren(),
                  isClean());
          params_ = null;
        }
        return paramsBuilder_;
      }

      private java.util.List<injective.wasmx.v1.Genesis.RegisteredContractWithAddress> registeredContracts_ =
        java.util.Collections.emptyList();
      private void ensureRegisteredContractsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          registeredContracts_ = new java.util.ArrayList<injective.wasmx.v1.Genesis.RegisteredContractWithAddress>(registeredContracts_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          injective.wasmx.v1.Genesis.RegisteredContractWithAddress, injective.wasmx.v1.Genesis.RegisteredContractWithAddress.Builder, injective.wasmx.v1.Genesis.RegisteredContractWithAddressOrBuilder> registeredContractsBuilder_;

      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<injective.wasmx.v1.Genesis.RegisteredContractWithAddress> getRegisteredContractsList() {
        if (registeredContractsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(registeredContracts_);
        } else {
          return registeredContractsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public int getRegisteredContractsCount() {
        if (registeredContractsBuilder_ == null) {
          return registeredContracts_.size();
        } else {
          return registeredContractsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public injective.wasmx.v1.Genesis.RegisteredContractWithAddress getRegisteredContracts(int index) {
        if (registeredContractsBuilder_ == null) {
          return registeredContracts_.get(index);
        } else {
          return registeredContractsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setRegisteredContracts(
          int index, injective.wasmx.v1.Genesis.RegisteredContractWithAddress value) {
        if (registeredContractsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRegisteredContractsIsMutable();
          registeredContracts_.set(index, value);
          onChanged();
        } else {
          registeredContractsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setRegisteredContracts(
          int index, injective.wasmx.v1.Genesis.RegisteredContractWithAddress.Builder builderForValue) {
        if (registeredContractsBuilder_ == null) {
          ensureRegisteredContractsIsMutable();
          registeredContracts_.set(index, builderForValue.build());
          onChanged();
        } else {
          registeredContractsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addRegisteredContracts(injective.wasmx.v1.Genesis.RegisteredContractWithAddress value) {
        if (registeredContractsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRegisteredContractsIsMutable();
          registeredContracts_.add(value);
          onChanged();
        } else {
          registeredContractsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addRegisteredContracts(
          int index, injective.wasmx.v1.Genesis.RegisteredContractWithAddress value) {
        if (registeredContractsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRegisteredContractsIsMutable();
          registeredContracts_.add(index, value);
          onChanged();
        } else {
          registeredContractsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addRegisteredContracts(
          injective.wasmx.v1.Genesis.RegisteredContractWithAddress.Builder builderForValue) {
        if (registeredContractsBuilder_ == null) {
          ensureRegisteredContractsIsMutable();
          registeredContracts_.add(builderForValue.build());
          onChanged();
        } else {
          registeredContractsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addRegisteredContracts(
          int index, injective.wasmx.v1.Genesis.RegisteredContractWithAddress.Builder builderForValue) {
        if (registeredContractsBuilder_ == null) {
          ensureRegisteredContractsIsMutable();
          registeredContracts_.add(index, builderForValue.build());
          onChanged();
        } else {
          registeredContractsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addAllRegisteredContracts(
          java.lang.Iterable<? extends injective.wasmx.v1.Genesis.RegisteredContractWithAddress> values) {
        if (registeredContractsBuilder_ == null) {
          ensureRegisteredContractsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, registeredContracts_);
          onChanged();
        } else {
          registeredContractsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearRegisteredContracts() {
        if (registeredContractsBuilder_ == null) {
          registeredContracts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          registeredContractsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder removeRegisteredContracts(int index) {
        if (registeredContractsBuilder_ == null) {
          ensureRegisteredContractsIsMutable();
          registeredContracts_.remove(index);
          onChanged();
        } else {
          registeredContractsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public injective.wasmx.v1.Genesis.RegisteredContractWithAddress.Builder getRegisteredContractsBuilder(
          int index) {
        return getRegisteredContractsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public injective.wasmx.v1.Genesis.RegisteredContractWithAddressOrBuilder getRegisteredContractsOrBuilder(
          int index) {
        if (registeredContractsBuilder_ == null) {
          return registeredContracts_.get(index);  } else {
          return registeredContractsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<? extends injective.wasmx.v1.Genesis.RegisteredContractWithAddressOrBuilder> 
           getRegisteredContractsOrBuilderList() {
        if (registeredContractsBuilder_ != null) {
          return registeredContractsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(registeredContracts_);
        }
      }
      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public injective.wasmx.v1.Genesis.RegisteredContractWithAddress.Builder addRegisteredContractsBuilder() {
        return getRegisteredContractsFieldBuilder().addBuilder(
            injective.wasmx.v1.Genesis.RegisteredContractWithAddress.getDefaultInstance());
      }
      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public injective.wasmx.v1.Genesis.RegisteredContractWithAddress.Builder addRegisteredContractsBuilder(
          int index) {
        return getRegisteredContractsFieldBuilder().addBuilder(
            index, injective.wasmx.v1.Genesis.RegisteredContractWithAddress.getDefaultInstance());
      }
      /**
       * <pre>
       * registered_contracts is an array containing the genesis registered
       * contracts
       * </pre>
       *
       * <code>repeated .injective.wasmx.v1.RegisteredContractWithAddress registered_contracts = 2 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<injective.wasmx.v1.Genesis.RegisteredContractWithAddress.Builder> 
           getRegisteredContractsBuilderList() {
        return getRegisteredContractsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          injective.wasmx.v1.Genesis.RegisteredContractWithAddress, injective.wasmx.v1.Genesis.RegisteredContractWithAddress.Builder, injective.wasmx.v1.Genesis.RegisteredContractWithAddressOrBuilder> 
          getRegisteredContractsFieldBuilder() {
        if (registeredContractsBuilder_ == null) {
          registeredContractsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              injective.wasmx.v1.Genesis.RegisteredContractWithAddress, injective.wasmx.v1.Genesis.RegisteredContractWithAddress.Builder, injective.wasmx.v1.Genesis.RegisteredContractWithAddressOrBuilder>(
                  registeredContracts_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          registeredContracts_ = null;
        }
        return registeredContractsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:injective.wasmx.v1.GenesisState)
    }

    // @@protoc_insertion_point(class_scope:injective.wasmx.v1.GenesisState)
    private static final injective.wasmx.v1.Genesis.GenesisState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new injective.wasmx.v1.Genesis.GenesisState();
    }

    public static injective.wasmx.v1.Genesis.GenesisState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenesisState>
        PARSER = new com.google.protobuf.AbstractParser<GenesisState>() {
      @java.lang.Override
      public GenesisState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GenesisState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenesisState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public injective.wasmx.v1.Genesis.GenesisState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_injective_wasmx_v1_RegisteredContractWithAddress_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_injective_wasmx_v1_RegisteredContractWithAddress_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_injective_wasmx_v1_GenesisState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_injective_wasmx_v1_GenesisState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n injective/wasmx/v1/genesis.proto\022\022inje" +
      "ctive.wasmx.v1\032\036injective/wasmx/v1/wasmx" +
      ".proto\032\024gogoproto/gogo.proto\"u\n\035Register" +
      "edContractWithAddress\022\017\n\007address\030\001 \001(\t\022C" +
      "\n\023registered_contract\030\002 \001(\0132&.injective." +
      "wasmx.v1.RegisteredContract\"\227\001\n\014GenesisS" +
      "tate\0220\n\006params\030\001 \001(\0132\032.injective.wasmx.v" +
      "1.ParamsB\004\310\336\037\000\022U\n\024registered_contracts\030\002" +
      " \003(\01321.injective.wasmx.v1.RegisteredCont" +
      "ractWithAddressB\004\310\336\037\000BMZKgithub.com/Inje" +
      "ctiveLabs/injective-core/injective-chain" +
      "/modules/wasmx/typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          injective.wasmx.v1.Wasmx.getDescriptor(),
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_injective_wasmx_v1_RegisteredContractWithAddress_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_injective_wasmx_v1_RegisteredContractWithAddress_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_injective_wasmx_v1_RegisteredContractWithAddress_descriptor,
        new java.lang.String[] { "Address", "RegisteredContract", });
    internal_static_injective_wasmx_v1_GenesisState_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_injective_wasmx_v1_GenesisState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_injective_wasmx_v1_GenesisState_descriptor,
        new java.lang.String[] { "Params", "RegisteredContracts", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    injective.wasmx.v1.Wasmx.getDescriptor();
    com.google.protobuf.GoGoProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
