// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: injective/permissions/v1beta1/events.proto

package injective.permissions.v1beta1;

public final class Events {
  private Events() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*injective/permissions/v1beta1/events.p" +
      "roto\022\035injective.permissions.v1beta1\032\024gog" +
      "oproto/gogo.proto\032\036cosmos/base/v1beta1/c" +
      "oin.proto\032\036cosmos/bank/v1beta1/bank.prot" +
      "oBSZQgithub.com/InjectiveLabs/injective-" +
      "core/injective-chain/modules/permissions" +
      "/typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
          cosmos.base.v1beta1.CoinOuterClass.getDescriptor(),
          cosmos.bank.v1beta1.Bank.getDescriptor(),
        });
    com.google.protobuf.GoGoProtos.getDescriptor();
    cosmos.base.v1beta1.CoinOuterClass.getDescriptor();
    cosmos.bank.v1beta1.Bank.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
