// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: injective/permissions/v1beta1/genesis.proto

package injective.permissions.v1beta1;

public final class Genesis {
  private Genesis() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GenesisStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:injective.permissions.v1beta1.GenesisState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * params defines the parameters of the module.
     * </pre>
     *
     * <code>.injective.permissions.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     * @return Whether the params field is set.
     */
    boolean hasParams();
    /**
     * <pre>
     * params defines the parameters of the module.
     * </pre>
     *
     * <code>.injective.permissions.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     * @return The params.
     */
    injective.permissions.v1beta1.ParamsOuterClass.Params getParams();
    /**
     * <pre>
     * params defines the parameters of the module.
     * </pre>
     *
     * <code>.injective.permissions.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     */
    injective.permissions.v1beta1.ParamsOuterClass.ParamsOrBuilder getParamsOrBuilder();

    /**
     * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
     */
    java.util.List<injective.permissions.v1beta1.Permissions.Namespace> 
        getNamespacesList();
    /**
     * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
     */
    injective.permissions.v1beta1.Permissions.Namespace getNamespaces(int index);
    /**
     * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
     */
    int getNamespacesCount();
    /**
     * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
     */
    java.util.List<? extends injective.permissions.v1beta1.Permissions.NamespaceOrBuilder> 
        getNamespacesOrBuilderList();
    /**
     * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
     */
    injective.permissions.v1beta1.Permissions.NamespaceOrBuilder getNamespacesOrBuilder(
        int index);
  }
  /**
   * <pre>
   * GenesisState defines the permissions module's genesis state.
   * </pre>
   *
   * Protobuf type {@code injective.permissions.v1beta1.GenesisState}
   */
  public static final class GenesisState extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:injective.permissions.v1beta1.GenesisState)
      GenesisStateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GenesisState.newBuilder() to construct.
    private GenesisState(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GenesisState() {
      namespaces_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GenesisState();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return injective.permissions.v1beta1.Genesis.internal_static_injective_permissions_v1beta1_GenesisState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return injective.permissions.v1beta1.Genesis.internal_static_injective_permissions_v1beta1_GenesisState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              injective.permissions.v1beta1.Genesis.GenesisState.class, injective.permissions.v1beta1.Genesis.GenesisState.Builder.class);
    }

    public static final int PARAMS_FIELD_NUMBER = 1;
    private injective.permissions.v1beta1.ParamsOuterClass.Params params_;
    /**
     * <pre>
     * params defines the parameters of the module.
     * </pre>
     *
     * <code>.injective.permissions.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     * @return Whether the params field is set.
     */
    @java.lang.Override
    public boolean hasParams() {
      return params_ != null;
    }
    /**
     * <pre>
     * params defines the parameters of the module.
     * </pre>
     *
     * <code>.injective.permissions.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     * @return The params.
     */
    @java.lang.Override
    public injective.permissions.v1beta1.ParamsOuterClass.Params getParams() {
      return params_ == null ? injective.permissions.v1beta1.ParamsOuterClass.Params.getDefaultInstance() : params_;
    }
    /**
     * <pre>
     * params defines the parameters of the module.
     * </pre>
     *
     * <code>.injective.permissions.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public injective.permissions.v1beta1.ParamsOuterClass.ParamsOrBuilder getParamsOrBuilder() {
      return params_ == null ? injective.permissions.v1beta1.ParamsOuterClass.Params.getDefaultInstance() : params_;
    }

    public static final int NAMESPACES_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<injective.permissions.v1beta1.Permissions.Namespace> namespaces_;
    /**
     * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public java.util.List<injective.permissions.v1beta1.Permissions.Namespace> getNamespacesList() {
      return namespaces_;
    }
    /**
     * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public java.util.List<? extends injective.permissions.v1beta1.Permissions.NamespaceOrBuilder> 
        getNamespacesOrBuilderList() {
      return namespaces_;
    }
    /**
     * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public int getNamespacesCount() {
      return namespaces_.size();
    }
    /**
     * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public injective.permissions.v1beta1.Permissions.Namespace getNamespaces(int index) {
      return namespaces_.get(index);
    }
    /**
     * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
     */
    @java.lang.Override
    public injective.permissions.v1beta1.Permissions.NamespaceOrBuilder getNamespacesOrBuilder(
        int index) {
      return namespaces_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (params_ != null) {
        output.writeMessage(1, getParams());
      }
      for (int i = 0; i < namespaces_.size(); i++) {
        output.writeMessage(2, namespaces_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (params_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getParams());
      }
      for (int i = 0; i < namespaces_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, namespaces_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof injective.permissions.v1beta1.Genesis.GenesisState)) {
        return super.equals(obj);
      }
      injective.permissions.v1beta1.Genesis.GenesisState other = (injective.permissions.v1beta1.Genesis.GenesisState) obj;

      if (hasParams() != other.hasParams()) return false;
      if (hasParams()) {
        if (!getParams()
            .equals(other.getParams())) return false;
      }
      if (!getNamespacesList()
          .equals(other.getNamespacesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasParams()) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParams().hashCode();
      }
      if (getNamespacesCount() > 0) {
        hash = (37 * hash) + NAMESPACES_FIELD_NUMBER;
        hash = (53 * hash) + getNamespacesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static injective.permissions.v1beta1.Genesis.GenesisState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.permissions.v1beta1.Genesis.GenesisState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.permissions.v1beta1.Genesis.GenesisState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.permissions.v1beta1.Genesis.GenesisState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.permissions.v1beta1.Genesis.GenesisState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static injective.permissions.v1beta1.Genesis.GenesisState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static injective.permissions.v1beta1.Genesis.GenesisState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static injective.permissions.v1beta1.Genesis.GenesisState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static injective.permissions.v1beta1.Genesis.GenesisState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static injective.permissions.v1beta1.Genesis.GenesisState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static injective.permissions.v1beta1.Genesis.GenesisState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static injective.permissions.v1beta1.Genesis.GenesisState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(injective.permissions.v1beta1.Genesis.GenesisState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * GenesisState defines the permissions module's genesis state.
     * </pre>
     *
     * Protobuf type {@code injective.permissions.v1beta1.GenesisState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:injective.permissions.v1beta1.GenesisState)
        injective.permissions.v1beta1.Genesis.GenesisStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return injective.permissions.v1beta1.Genesis.internal_static_injective_permissions_v1beta1_GenesisState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return injective.permissions.v1beta1.Genesis.internal_static_injective_permissions_v1beta1_GenesisState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                injective.permissions.v1beta1.Genesis.GenesisState.class, injective.permissions.v1beta1.Genesis.GenesisState.Builder.class);
      }

      // Construct using injective.permissions.v1beta1.Genesis.GenesisState.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        params_ = null;
        if (paramsBuilder_ != null) {
          paramsBuilder_.dispose();
          paramsBuilder_ = null;
        }
        if (namespacesBuilder_ == null) {
          namespaces_ = java.util.Collections.emptyList();
        } else {
          namespaces_ = null;
          namespacesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return injective.permissions.v1beta1.Genesis.internal_static_injective_permissions_v1beta1_GenesisState_descriptor;
      }

      @java.lang.Override
      public injective.permissions.v1beta1.Genesis.GenesisState getDefaultInstanceForType() {
        return injective.permissions.v1beta1.Genesis.GenesisState.getDefaultInstance();
      }

      @java.lang.Override
      public injective.permissions.v1beta1.Genesis.GenesisState build() {
        injective.permissions.v1beta1.Genesis.GenesisState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public injective.permissions.v1beta1.Genesis.GenesisState buildPartial() {
        injective.permissions.v1beta1.Genesis.GenesisState result = new injective.permissions.v1beta1.Genesis.GenesisState(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(injective.permissions.v1beta1.Genesis.GenesisState result) {
        if (namespacesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            namespaces_ = java.util.Collections.unmodifiableList(namespaces_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.namespaces_ = namespaces_;
        } else {
          result.namespaces_ = namespacesBuilder_.build();
        }
      }

      private void buildPartial0(injective.permissions.v1beta1.Genesis.GenesisState result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.params_ = paramsBuilder_ == null
              ? params_
              : paramsBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof injective.permissions.v1beta1.Genesis.GenesisState) {
          return mergeFrom((injective.permissions.v1beta1.Genesis.GenesisState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(injective.permissions.v1beta1.Genesis.GenesisState other) {
        if (other == injective.permissions.v1beta1.Genesis.GenesisState.getDefaultInstance()) return this;
        if (other.hasParams()) {
          mergeParams(other.getParams());
        }
        if (namespacesBuilder_ == null) {
          if (!other.namespaces_.isEmpty()) {
            if (namespaces_.isEmpty()) {
              namespaces_ = other.namespaces_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureNamespacesIsMutable();
              namespaces_.addAll(other.namespaces_);
            }
            onChanged();
          }
        } else {
          if (!other.namespaces_.isEmpty()) {
            if (namespacesBuilder_.isEmpty()) {
              namespacesBuilder_.dispose();
              namespacesBuilder_ = null;
              namespaces_ = other.namespaces_;
              bitField0_ = (bitField0_ & ~0x00000002);
              namespacesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNamespacesFieldBuilder() : null;
            } else {
              namespacesBuilder_.addAllMessages(other.namespaces_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getParamsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                injective.permissions.v1beta1.Permissions.Namespace m =
                    input.readMessage(
                        injective.permissions.v1beta1.Permissions.Namespace.parser(),
                        extensionRegistry);
                if (namespacesBuilder_ == null) {
                  ensureNamespacesIsMutable();
                  namespaces_.add(m);
                } else {
                  namespacesBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private injective.permissions.v1beta1.ParamsOuterClass.Params params_;
      private com.google.protobuf.SingleFieldBuilderV3<
          injective.permissions.v1beta1.ParamsOuterClass.Params, injective.permissions.v1beta1.ParamsOuterClass.Params.Builder, injective.permissions.v1beta1.ParamsOuterClass.ParamsOrBuilder> paramsBuilder_;
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>.injective.permissions.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       * @return Whether the params field is set.
       */
      public boolean hasParams() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>.injective.permissions.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       * @return The params.
       */
      public injective.permissions.v1beta1.ParamsOuterClass.Params getParams() {
        if (paramsBuilder_ == null) {
          return params_ == null ? injective.permissions.v1beta1.ParamsOuterClass.Params.getDefaultInstance() : params_;
        } else {
          return paramsBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>.injective.permissions.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setParams(injective.permissions.v1beta1.ParamsOuterClass.Params value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          params_ = value;
        } else {
          paramsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>.injective.permissions.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setParams(
          injective.permissions.v1beta1.ParamsOuterClass.Params.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          params_ = builderForValue.build();
        } else {
          paramsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>.injective.permissions.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder mergeParams(injective.permissions.v1beta1.ParamsOuterClass.Params value) {
        if (paramsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            params_ != null &&
            params_ != injective.permissions.v1beta1.ParamsOuterClass.Params.getDefaultInstance()) {
            getParamsBuilder().mergeFrom(value);
          } else {
            params_ = value;
          }
        } else {
          paramsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>.injective.permissions.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearParams() {
        bitField0_ = (bitField0_ & ~0x00000001);
        params_ = null;
        if (paramsBuilder_ != null) {
          paramsBuilder_.dispose();
          paramsBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>.injective.permissions.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       */
      public injective.permissions.v1beta1.ParamsOuterClass.Params.Builder getParamsBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getParamsFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>.injective.permissions.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       */
      public injective.permissions.v1beta1.ParamsOuterClass.ParamsOrBuilder getParamsOrBuilder() {
        if (paramsBuilder_ != null) {
          return paramsBuilder_.getMessageOrBuilder();
        } else {
          return params_ == null ?
              injective.permissions.v1beta1.ParamsOuterClass.Params.getDefaultInstance() : params_;
        }
      }
      /**
       * <pre>
       * params defines the parameters of the module.
       * </pre>
       *
       * <code>.injective.permissions.v1beta1.Params params = 1 [(.gogoproto.nullable) = false];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          injective.permissions.v1beta1.ParamsOuterClass.Params, injective.permissions.v1beta1.ParamsOuterClass.Params.Builder, injective.permissions.v1beta1.ParamsOuterClass.ParamsOrBuilder> 
          getParamsFieldBuilder() {
        if (paramsBuilder_ == null) {
          paramsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              injective.permissions.v1beta1.ParamsOuterClass.Params, injective.permissions.v1beta1.ParamsOuterClass.Params.Builder, injective.permissions.v1beta1.ParamsOuterClass.ParamsOrBuilder>(
                  getParams(),
                  getParentForChildren(),
                  isClean());
          params_ = null;
        }
        return paramsBuilder_;
      }

      private java.util.List<injective.permissions.v1beta1.Permissions.Namespace> namespaces_ =
        java.util.Collections.emptyList();
      private void ensureNamespacesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          namespaces_ = new java.util.ArrayList<injective.permissions.v1beta1.Permissions.Namespace>(namespaces_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          injective.permissions.v1beta1.Permissions.Namespace, injective.permissions.v1beta1.Permissions.Namespace.Builder, injective.permissions.v1beta1.Permissions.NamespaceOrBuilder> namespacesBuilder_;

      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<injective.permissions.v1beta1.Permissions.Namespace> getNamespacesList() {
        if (namespacesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(namespaces_);
        } else {
          return namespacesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public int getNamespacesCount() {
        if (namespacesBuilder_ == null) {
          return namespaces_.size();
        } else {
          return namespacesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public injective.permissions.v1beta1.Permissions.Namespace getNamespaces(int index) {
        if (namespacesBuilder_ == null) {
          return namespaces_.get(index);
        } else {
          return namespacesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setNamespaces(
          int index, injective.permissions.v1beta1.Permissions.Namespace value) {
        if (namespacesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNamespacesIsMutable();
          namespaces_.set(index, value);
          onChanged();
        } else {
          namespacesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder setNamespaces(
          int index, injective.permissions.v1beta1.Permissions.Namespace.Builder builderForValue) {
        if (namespacesBuilder_ == null) {
          ensureNamespacesIsMutable();
          namespaces_.set(index, builderForValue.build());
          onChanged();
        } else {
          namespacesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addNamespaces(injective.permissions.v1beta1.Permissions.Namespace value) {
        if (namespacesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNamespacesIsMutable();
          namespaces_.add(value);
          onChanged();
        } else {
          namespacesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addNamespaces(
          int index, injective.permissions.v1beta1.Permissions.Namespace value) {
        if (namespacesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNamespacesIsMutable();
          namespaces_.add(index, value);
          onChanged();
        } else {
          namespacesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addNamespaces(
          injective.permissions.v1beta1.Permissions.Namespace.Builder builderForValue) {
        if (namespacesBuilder_ == null) {
          ensureNamespacesIsMutable();
          namespaces_.add(builderForValue.build());
          onChanged();
        } else {
          namespacesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addNamespaces(
          int index, injective.permissions.v1beta1.Permissions.Namespace.Builder builderForValue) {
        if (namespacesBuilder_ == null) {
          ensureNamespacesIsMutable();
          namespaces_.add(index, builderForValue.build());
          onChanged();
        } else {
          namespacesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder addAllNamespaces(
          java.lang.Iterable<? extends injective.permissions.v1beta1.Permissions.Namespace> values) {
        if (namespacesBuilder_ == null) {
          ensureNamespacesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, namespaces_);
          onChanged();
        } else {
          namespacesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder clearNamespaces() {
        if (namespacesBuilder_ == null) {
          namespaces_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          namespacesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public Builder removeNamespaces(int index) {
        if (namespacesBuilder_ == null) {
          ensureNamespacesIsMutable();
          namespaces_.remove(index);
          onChanged();
        } else {
          namespacesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public injective.permissions.v1beta1.Permissions.Namespace.Builder getNamespacesBuilder(
          int index) {
        return getNamespacesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public injective.permissions.v1beta1.Permissions.NamespaceOrBuilder getNamespacesOrBuilder(
          int index) {
        if (namespacesBuilder_ == null) {
          return namespaces_.get(index);  } else {
          return namespacesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<? extends injective.permissions.v1beta1.Permissions.NamespaceOrBuilder> 
           getNamespacesOrBuilderList() {
        if (namespacesBuilder_ != null) {
          return namespacesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(namespaces_);
        }
      }
      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public injective.permissions.v1beta1.Permissions.Namespace.Builder addNamespacesBuilder() {
        return getNamespacesFieldBuilder().addBuilder(
            injective.permissions.v1beta1.Permissions.Namespace.getDefaultInstance());
      }
      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public injective.permissions.v1beta1.Permissions.Namespace.Builder addNamespacesBuilder(
          int index) {
        return getNamespacesFieldBuilder().addBuilder(
            index, injective.permissions.v1beta1.Permissions.Namespace.getDefaultInstance());
      }
      /**
       * <code>repeated .injective.permissions.v1beta1.Namespace namespaces = 2 [(.gogoproto.nullable) = false];</code>
       */
      public java.util.List<injective.permissions.v1beta1.Permissions.Namespace.Builder> 
           getNamespacesBuilderList() {
        return getNamespacesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          injective.permissions.v1beta1.Permissions.Namespace, injective.permissions.v1beta1.Permissions.Namespace.Builder, injective.permissions.v1beta1.Permissions.NamespaceOrBuilder> 
          getNamespacesFieldBuilder() {
        if (namespacesBuilder_ == null) {
          namespacesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              injective.permissions.v1beta1.Permissions.Namespace, injective.permissions.v1beta1.Permissions.Namespace.Builder, injective.permissions.v1beta1.Permissions.NamespaceOrBuilder>(
                  namespaces_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          namespaces_ = null;
        }
        return namespacesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:injective.permissions.v1beta1.GenesisState)
    }

    // @@protoc_insertion_point(class_scope:injective.permissions.v1beta1.GenesisState)
    private static final injective.permissions.v1beta1.Genesis.GenesisState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new injective.permissions.v1beta1.Genesis.GenesisState();
    }

    public static injective.permissions.v1beta1.Genesis.GenesisState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GenesisState>
        PARSER = new com.google.protobuf.AbstractParser<GenesisState>() {
      @java.lang.Override
      public GenesisState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GenesisState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GenesisState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public injective.permissions.v1beta1.Genesis.GenesisState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_injective_permissions_v1beta1_GenesisState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_injective_permissions_v1beta1_GenesisState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+injective/permissions/v1beta1/genesis." +
      "proto\022\035injective.permissions.v1beta1\032\024go" +
      "goproto/gogo.proto\032*injective/permission" +
      "s/v1beta1/params.proto\032/injective/permis" +
      "sions/v1beta1/permissions.proto\"\217\001\n\014Gene" +
      "sisState\022;\n\006params\030\001 \001(\0132%.injective.per" +
      "missions.v1beta1.ParamsB\004\310\336\037\000\022B\n\nnamespa" +
      "ces\030\002 \003(\0132(.injective.permissions.v1beta" +
      "1.NamespaceB\004\310\336\037\000BSZQgithub.com/Injectiv" +
      "eLabs/injective-core/injective-chain/mod" +
      "ules/permissions/typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
          injective.permissions.v1beta1.ParamsOuterClass.getDescriptor(),
          injective.permissions.v1beta1.Permissions.getDescriptor(),
        });
    internal_static_injective_permissions_v1beta1_GenesisState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_injective_permissions_v1beta1_GenesisState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_injective_permissions_v1beta1_GenesisState_descriptor,
        new java.lang.String[] { "Params", "Namespaces", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
    injective.permissions.v1beta1.ParamsOuterClass.getDescriptor();
    injective.permissions.v1beta1.Permissions.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
